
FROM node:20 as builder


WORKDIR /app


COPY package.json package-lock.json ./
RUN npm install --production


COPY . .


RUN npm run build


FROM node:20-alpine


WORKDIR /app


COPY --from=builder /app/package.json /app/package-lock.json /app/
COPY --from=builder /app/.next /app/.next
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/public /app/public


ENV NODE_ENV=production


EXPOSE 3000


CMD ["npm", "run", "start"]
